In [1]:
# Initialize Otter
import otter

grader = otter.Notebook("fifa_21_raw_data.ipynb")

## Week 2 - FIFA '21 Player Ratings

This notebook is created for the week 2 assignment. Here, you have a very messy and raw dataset of EA Sports' installment of their hit FIFA series - FIFA21, which was scraped from sofifa.com.

Your task in this assignment is to clean up this dataset using the `Hints` provided in the ReadMe file

In [2]:
import pandas as pd
import numpy as np
import os
%matplotlib inline
import otter
grader = otter.Notebook()

**Question 1:** Load the fifa dataset into a variable called `fifa_dataset`. Next, write a function called `check_data` to check if the `fifa_dataset` is empty or not by returning True or False.

In [3]:
fifa_dataset = pd.read_csv('fifa_21_raw_data.csv', dtype={'Hits': str}, engine='python')

fifa_dataset.head()

def check_data(fifa_dataset):
   if fifa_dataset.empty:
      return True
   else:
      return False

In [4]:
grader.check("q1")

q1 results: All test cases passed!

**Question 1:** Load the fifa dataset into a variable called `fifa_dataset`. Next, write a function called `check_data` to check if the `fifa_dataset` is empty or not by returning True or False.

**Question 2:** Remove all duplicate player `name` from the dataset. Remember, you need to leave the first occurence and remove other ones.

In [5]:
def remove_duplicate(dataset):
    return dataset.drop_duplicates(subset=['Name'], keep='first')

In [ ]:
grader.check("q2")

**Question 1:** Load the fifa dataset into a variable called `fifa_dataset`. Next, write a function called `check_data` to check if the `fifa_dataset` is empty or not by returning True or False.

**Question 3:** Remove all leading white spaces or newline "\n" in the `club` column. For example, `"\n\n\n\nFC Barcelona"` should be transformed into `"FC Barcelona"`

In [7]:
def remove_newline(dataset):
    string_cols = dataset.select_dtypes(include='str').columns
    dataset[string_cols] = dataset[string_cols].apply(lambda col: col.str.strip())
    return dataset

In [8]:
grader.check("q3")

q3 results: All test cases passed!

**Question 4:** List the TOP 5 countries with the highest number of representation of players in the data. Create a dictionary called `top_5_country` using the country names as the key and the number of players as the value. For example,

`top_5_country` = {'Kenya': 15,
                  'Nigeria': 45,
                  'Ghana': 14,
                  'Canada': 20,
                  'USA': 88
                 }

Added: converted weight and height into integer datatypes e.g., 10kg -> 10

In [ ]:
top_5_country = fifa_dataset['Nationality'].value_counts().head(5)

top_5_country = top_5_country.to_dict()

print(top_5_country)

fifa_dataset = remove_duplicate(remove_newline(fifa_dataset))

#convert weight and height into integer datatypes e.g., 10kg -> 10

def convert_weight(value):
    if isinstance(value, int) or isinstance(value, float):
        return int(value)  # already a number, just return it
    if 'kg' in value:
        return int(value.replace('kg', ''))
    elif 'lbs' in value:
        return round(int(value.replace('lbs', '')) * 0.453592)
    
fifa_dataset['Weight'] = fifa_dataset['Weight'].apply(convert_weight)

if fifa_dataset['Height'].dtype not in ['int64', 'float64']:  # only run if it's not already a number
    fifa_dataset['Height'] = fifa_dataset['Height'].str.extract(r'(\d+)').astype(int)

{'England': 1574, 'Germany': 1178, 'Spain': 1019, 'France': 971, 'Argentina': 861}

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,First Name,Last Name
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,FC Barcelona,...,5 ★,85,92,91,95,38,65,771,Lionel,Messi
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,Juventus,...,5 ★,89,93,81,89,35,77,562,C.,Ronaldo dos Santos Aveiro
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,Atlético Madrid,...,3 ★,87,92,78,90,52,90,150,Jan,Oblak
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,Manchester City,...,4 ★,76,86,93,88,64,78,207,Kevin,De Bruyne
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,Paris Saint-Germain,...,5 ★,91,85,86,94,36,59,595,Neymar,da Silva Santos Jr.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47,55,Wuhan Zall,...,1 ★,64,28,26,38,48,51,NaN,Ao,Xia
18975,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47,67,Oldham Athletic,...,1 ★,64,40,48,49,35,45,NaN,Ben,Hough
18976,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47,65,Derry City,...,1 ★,63,39,44,46,40,53,NaN,Ronan,McKinley
18977,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47,57,Dalian YiFang FC,...,1 ★,58,49,41,49,30,44,NaN,Zhen'ao,Wang
18978,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47,57,Dalian YiFang FC,...,1 ★,62,22,39,42,45,55,NaN,Xiao,Zhou

Break the "Long Name" into two columns with first name and last name

In [25]:
fifa_dataset['First Name'] = fifa_dataset['LongName'].str.split(' ').str[0]
fifa_dataset['Last Name'] = fifa_dataset['LongName'].str.split(' ').str[1:].str.join(' ')

# Get current columns as a list
cols = fifa_dataset.columns.tolist()

# Remove First Name and Last Name from wherever they are
cols.remove('First Name')
cols.remove('Last Name')

# Find where LongName is and insert after it
long_name_idx = cols.index('LongName')
cols.insert(long_name_idx + 1, 'First Name')
cols.insert(long_name_idx + 2, 'Last Name')

# Reorder the DataFrame
fifa_dataset = fifa_dataset[cols]

fifa_dataset.head()

,ID,Name,LongName,First Name,Last Name,photoUrl,playerUrl,Nationality,Age,↓OVA,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,Lionel,Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,C.,Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,Jan,Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,Kevin,De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,Neymar,da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,...,High,Medium,5 ★,91,85,86,94,36,59,595

We want to identify outliers in the "Age" column. In this case, we'll use the Standard Deviation (SD) Formula for 4 sds away from the mean

In [ ]:
#check for outliers in the age that are 4 standard deviations away from the mean

min_limit = fifa_dataset['Age'].mean() - 4 * fifa_dataset['Age'].std()
max_limit = fifa_dataset['Age'].mean() + 4 * fifa_dataset['Age'].std()

min_limit,max_limit

fifa_dataset[(fifa_dataset['Age'] < max_limit) & (fifa_dataset['Age'] > min_limit)]

,ID,Name,LongName,First Name,Last Name,photoUrl,playerUrl,Nationality,Age,↓OVA,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,Lionel,Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,C.,Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,Jan,Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,Kevin,De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,Neymar,da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,...,High,Medium,5 ★,91,85,86,94,36,59,595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,247223,Xia Ao,Ao Xia,Ao,Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47,...,Medium,Medium,1 ★,64,28,26,38,48,51,NaN
18975,258760,B. Hough,Ben Hough,Ben,Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47,...,Medium,Medium,1 ★,64,40,48,49,35,45,NaN
18976,252757,R. McKinley,Ronan McKinley,Ronan,McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47,...,Medium,Medium,1 ★,63,39,44,46,40,53,NaN
18977,243790,Wang Zhen'ao,Zhen'ao Wang,Zhen'ao,Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47,...,Medium,Medium,1 ★,58,49,41,49,30,44,NaN
18978,252520,Zhou Xiao,Xiao Zhou,Xiao,Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47,...,Medium,Medium,1 ★,62,22,39,42,45,55,NaN

In [11]:
grader.check("q4")

q4 results: All test cases passed!

<!-- BEGIN QUESTION -->

**Question 5:** What insight can you derive from this data?

We've 17920 uique players from 18979
Our players are aged 25 on average with 16 years old being the younges and 53 being the oldest 
England seems to have the highest number of players, followed immediately by Germany and Spain

<!-- END QUESTION -->

## Submission

Make sure you have run all cells in your notebook in order before running the cell below, so that all images/graphs appear in the output. The cell below will generate a zip file for you to submit. **Please save before exporting!**

These are some submission instructions.

In [12]:
# Save your notebook first, then run this cell to export your submission.
grader.export(run_tests=True, pdf=False)

Running your submission against local test cases...


Your submission received the following results when run against available test cases:

/Users/chukwuemekaokonkwo/Applications/IDS/ids-fifa-21-player-ratings/venv/lib/python3.14/site-packages/otter/check/utils.py:115: RuntimeWarning: [IPKernelApp] WARNING | Kernel is running over TCP without encryption. All communication (including code and outputs) is sent in plain text and is susceptible to eavesdropping. Use IPC transport or launch with kernel manager-provisioned CurveZMQ keys to enable transport encryption.

  warnings.warn(results.stderr.decode("utf-8"), RuntimeWarning)